"""add ingestion lifecycle fields to dataset

Revision ID: 8f8155d7f8cd
Revises: aa8d7bd3bb51
Create Date: 2026-01-22 00:13:43.200704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f8155d7f8cd'
down_revision: Union[str, Sequence[str], None] = 'aa8d7bd3bb51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'error_message')
    # ### end Alembic commands ###
