# app/core/query_engine.py

def execute_plan(df, plan: dict):
    """
    Executes a structured plan generated by the AI planner.

    This function is deterministic and safe.
    No LLM execution happens here.
    """

    operation = plan.get("operation")

    if operation != "aggregate":
        raise ValueError("Unsupported operation")

    aggregation = plan.get("aggregation")
    target = plan.get("target_column")
    group_by = plan.get("group_by")
    ranking = plan.get("ranking")

    if not aggregation or not target:
        raise ValueError("Invalid aggregation plan")

    # 🧠 Case 1 — Grouped Aggregation
    if group_by:
        if group_by not in df.columns:
            raise ValueError(f"Column '{group_by}' not found")

        if target not in df.columns:
            raise ValueError(f"Column '{target}' not found")

        # Perform aggregation safely
        grouped = getattr(
            df.groupby(group_by)[target],
            aggregation
        )()

        # Ranking (max / min)
        if ranking == "max":
            idx = grouped.idxmax()
            value = grouped.loc[idx]
            return f"{idx} has the highest {target} ({value})"

        if ranking == "min":
            idx = grouped.idxmin()
            value = grouped.loc[idx]
            return f"{idx} has the lowest {target} ({value})"

        # No ranking → return full grouped result
        return grouped.to_dict()

    # 🧠 Case 2 — No Grouping (Global aggregation)
    else:
        if target not in df.columns:
            raise ValueError(f"Column '{target}' not found")

        result = getattr(df[target], aggregation)()
        return f"{aggregation} of {target} is {result}"
